### ISSUE TITLE
Draggabilly not optional again

### ISSUE THREAD

**Issue by rfontanella** [puranjayjain/md-date-time-picker#212]
It's mentioned  [HERE](https://github.com/puranjayjain/md-date-time-picker) that the Draggabilly is an optional dependency, but when not including it javascript returns an error _Draggabilly2.default is not a constructor and the window doesn't open.

As far as I'm aware there is no flag to set to disable or enable the usage of Draggabilly 

This is a copy of the old #196 issue, bu the problem come back
Test it on [JsFiddle](https://jsfiddle.net/8uf0jzp4/2/)

**Comment by puranjayjain** [comment]
@digitalkaoz we had this problem fixed in a PR right?
I will need to recheck it. 
Also removing the optional message from docs until we can figure out how to actually make it optional.

**Comment by rfontanella** [comment]
@puranjayjain and @digitalkaoz 
If it helps, commenting line 505 ( this._dragDial(); ) solve the problem and keep the plugin working.
You probably just need a boolean setting to allow/disallow draggability!

**Comment by puranjayjain** [comment]
@rfontanella we could actually make a guard condition to make it work. Great suggestion btw.

**Comment by saha-kpghoshal** [comment]
@puranjayjain As of the latest code the bug exists. moreover the code refers Draggabilly as 'draggabilly' but in the file draggabilly.pkgd.js, it is exported as Draggabilly. hence its never found in the script even if Draggabilly is included in the page. it results in a '_draggabilly2.default is not a constructor' error.

**Comment by macx** [comment]
@puranjayjain This bug is still present. I could not init any time dial. But according to the tip of @rfontanella by removing `this_dragDial()` I could it make work. Please take your time and fix it!

**Comment by macx** [comment]
Investigated this issue using the demo which comes with this gulp build: The time picker is not working. Commenting this line it will bring the demo back to life: https://github.com/puranjayjain/md-date-time-picker/blob/master/src/js/mdDateTimePicker.js#L13

**Comment by slevy85** [comment]
The time picker works when I use with draggabilly 2.2.0
